theme: jekyll-theme-minimal
title: Awesome Scholarly Data Analysis
description: A curated collection of data related to scholarly publications for analysis, NLP, and information extraction. Maintained by [Shubhanshu Mishra](https://shubhanshu.com)
google_analytics: UA-44393164-1
