theme: jekyll-theme-minimal
title: Awesome Scholarly Data Analysis
description: A curated collection of resources on scholarly data analysis ranging from datasets, papers, and code about bibliometrics, citation analysis, and other scholarly commons resources. Maintained by <a href="https://shubhanshu.com">Shubhanshu Mishra</a>
google_analytics: UA-44393164-1
